services:
  db:
    image: postgres:16-alpine
    container_name: postgres-test
    ports:
      - "5432:5432"
    volumes:
      - ./backup:/var/backups
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    labels:
      - "dk.vsnt.backup.enabled=true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local
